### ISSUE TITLE
Node cli throws exception when piped to less and escaped before done rendering

### ISSUE THREAD

**Issue by ukilon-okta** [CSSLint/csslint#323]
To reproduce:
have a css that has an output omits a single page of output and pipe it to less

$`csslint file.css | less`

hit `:q`

Error:

```
fs.js:429
  return binding.write(fd, buffer, offset, length, position);
                 ^
Error: EPIPE, broken pipe
    at Object.fs.writeSync (fs.js:429:18)
    at Object.cli.print (/usr/local/lib/node_modules/csslint/cli.js:282:12)
    at processFile (/usr/local/lib/node_modules/csslint/cli.js:111:21)
    at /usr/local/lib/node_modules/csslint/cli.js:172:36
    at Array.forEach (native)
    at processFiles (/usr/local/lib/node_modules/csslint/cli.js:170:23)
    at cli (/usr/local/lib/node_modules/csslint/cli.js:265:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/csslint/cli.js:278:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

**Comment by lkraav** [comment]
Duplicate of #402
