### ISSUE TITLE
Error: ENOENT, no such file or directory '///dev/fd/9'

### ISSUE THREAD

**Issue by bancer** [CSSLint/csslint#636]
Executing `csslint --help` results in an error:

```
fs.js:689
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '///dev/fd/9'
    at Object.fs.statSync (fs.js:689:18)
    at /usr/local/lib/node_modules/csslint/cli.js:407:31
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/csslint/cli.js:405:45)
    at /usr/local/lib/node_modules/csslint/cli.js:414:21
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/csslint/cli.js:405:45)
    at /usr/local/lib/node_modules/csslint/cli.js:414:21
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/csslint/cli.js:405:45)
val@val-desktop:~/git/dinnerbooking.com$
`

**Comment by bancer** [comment]
This is caused by a comment in .csslintrc that starts with `//`.
