### ISSUE TITLE
Parsing fails for @page rules with margins

### ISSUE THREAD

**Issue by kovidgoyal** [CSSLint/csslint#764]
```
echo '@page { margin-bottom: 0 }' | csslint /dev/stdin                                                                  


csslint: There is 1 problem in /dev/stdin.

stdin
1: error at line undefined, col undefined
Fatal error, cannot continue: Cannot set property 'margin-bottom' of undefined
```

```
csslint --version                                                                                                       
v1.0.4
```

**Comment by kovidgoyal** [comment]
And here is a stacktrace against csslint.js
```
csslint.js:7841:TypeError: Cannot set property 'margin-bottom' of undefined
    at Parser.<anonymous> (userscript:csslint.js:9858:34)
    at Parser.fire (userscript:csslint.js:6478:30)
    at Parser._declaration (userscript:csslint.js:2523:26)
    at Parser._readDeclarations (userscript:csslint.js:3062:41)
    at Parser._page (userscript:csslint.js:1481:22)
    at Parser._stylesheet (userscript:csslint.js:871:38)
    at Parser.parse (userscript:csslint.js:3168:22)
    at EventTarget.api.verify (userscript:csslint.js:7839:20)
```
